local A = FonzAppraiser

A.module 'fa.filter'

local L = AceLibrary("AceLocale-2.2"):new("FonzAppraiser")

local util = A.requires(
  'util.string'
)

local groups = {
  [L["herbalism"]] = {
    [L["Arthas' Tears"]] = true,
    [L["Black Lotus"]] = true,
    [L["Blindweed"]] = true,
    [L["Bloodvine"]] = true,
    [L["Briarthorn"]] = true,
    [L["Bruiseweed"]] = true,
    [L["Dreamfoil"]] = true,
    [L["Earthroot"]] = true,
    [L["Fadeleaf"]] = true,
    [L["Firebloom"]] = true,
    [L["Ghost Mushroom"]] = true,
    [L["Golden Sansam"]] = true,
    [L["Goldthorn"]] = true,
    [L["Grave Moss"]] = true,
    [L["Gromsblood"]] = true,
    [L["Icecap"]] = true,
    [L["Khadgar's Whisker"]] = true,
    [L["Kingsblood"]] = true,
    [L["Liferoot"]] = true,
    [L["Mageroyal"]] = true,
    [L["Mountain Silversage"]] = true,
    [L["Peacebloom"]] = true,
    [L["Plaguebloom"]] = true,
    [L["Purple Lotus"]] = true,
    [L["Silverleaf"]] = true,
    [L["Stranglekelp"]] = true,
    [L["Sungrass"]] = true,
    [L["Swiftthistle"]] = true,
    [L["Wild Steelbloom"]] = true,
    [L["Wildvine"]] = true,
    [L["Wintersbite"]] = true,
  },
  [L["mining"]] = {
    [L["Aquamarine"]] = true,
    [L["Arcane Crystal"]] = true,
    [L["Azerothian Diamond"]] = true,
    [L["Black Diamond"]] = true,
    [L["Black Vitriol"]] = true,
    [L["Blood of the Mountain"]] = true,
    [L["Blue Sapphire"]] = true,
    [L["Citrine"]] = true,
    [L["Coarse Stone"]] = true,
    [L["Copper Ore"]] = true,
    [L["Dark Iron Ore"]] = true,
    [L["Dense Stone"]] = true,
    [L["Elemental Earth"]] = true,
    [L["Essence of Earth"]] = true,
    [L["Gold Ore"]] = true,
    [L["Heavy Stone"]] = true,
    [L["Huge Emerald"]] = true,
    [L["Iron Ore"]] = true,
    [L["Jade"]] = true,
    [L["Large Obsidian Shard"]] = true,
    [L["Large Opal"]] = true,
    [L["Lesser Moonstone"]] = true,
    [L["Malachite"]] = true,
    [L["Mithril Ore"]] = true,
    [L["Moss Agate"]] = true,
    [L["Rough Stone"]] = true,
    [L["Shadowgem"]] = true,
    [L["Silver Ore"]] = true,
    [L["Small Obsidian Shard"]] = true,
    [L["Solid Stone"]] = true,
    [L["Souldarite"]] = true,
    [L["Star Ruby"]] = true,
    [L["Thorium Ore"]] = true,
    [L["Tigerseye"]] = true,
    [L["Tin Ore"]] = true,
    [L["Truesilver Ore"]] = true,
  },
  [L["skinning"]] = {
    [L["Black Dragonscale"]] = true,
    [L["Black Whelp Scale"]] = true,
    [L["Blue Dragonscale"]] = true,
    [L["Brilliant Chromatic Scale"]] = true,
    [L["Chimera Leather"]] = true,
    [L["Core Leather"]] = true,
    [L["Deviate Scale"]] = true,
    [L["Devilsaur Leather"]] = true,
    [L["Dreamscale"]] = true,
    [L["Frostsaber Leather"]] = true,
    [L["Green Dragonscale"]] = true,
    [L["Green Whelp Scale"]] = true,
    [L["Heavy Hide"]] = true,
    [L["Heavy Leather"]] = true,
    [L["Heavy Scorpid Scale"]] = true,
    [L["Heavy Silithid Carapace"]] = true,
    [L["Light Hide"]] = true,
    [L["Light Leather"]] = true,
    [L["Light Silithid Carapace"]] = true,
    [L["Medium Hide"]] = true,
    [L["Medium Leather"]] = true,
    [L["Perfect Deviate Scale"]] = true,
    [L["Primal Bat Leather"]] = true,
    [L["Primal Tiger Leather"]] = true,
    [L["Red Dragonscale"]] = true,
    [L["Red Whelp Scale"]] = true,
    [L["Rugged Hide"]] = true,
    [L["Rugged Leather"]] = true,
    [L["Ruined Leather Scraps"]] = true,
    [L["Scale of Onyxia"]] = true,
    [L["Scorpid Scale"]] = true,
    [L["Shadowcat Hide"]] = true,
    [L["Silithid Chitin"]] = true,
    [L["Thick Hide"]] = true,
    [L["Thick Leather"]] = true,
    [L["Thick Wolfhide"]] = true,
    [L["Turtle Scale"]] = true,
    [L["Warbear Leather"]] = true,
    [L["Worn Dragonscale"]] = true,
  },
  [L["fishing"]] = {
    [L["Darkclaw Lobster"]] = true,
    [L["Deviate Fish"]] = true,
    [L["Elemental Water"]] = true,
    [L["Essence of Water"]] = true,
    [L["Firefin Snapper"]] = true,
    [L["Large Raw Mightfish"]] = true,
    [L["Oily Blackmouth"]] = true,
    [L["Raw Brilliant Smallfish"]] = true,
    [L["Raw Bristle Whisker Catfish"]] = true,
    [L["Raw Glossy Mightfish"]] = true,
    [L["Raw Greater Sagefish"]] = true,
    [L["Raw Loch Frenzy"]] = true,
    [L["Raw Longjaw Mud Snapper"]] = true,
    [L["Raw Mithril Head Trout"]] = true,
    [L["Raw Nightfin Snapper"]] = true,
    [L["Raw Rainbow Fin Albacore"]] = true,
    [L["Raw Redgill"]] = true,
    [L["Raw Rockscale Cod"]] = true,
    [L["Raw Sagefish"]] = true,
    [L["Raw Slitherskin Mackerel"]] = true,
    [L["Raw Spotted Yellowtail"]] = true,
    [L["Raw Summer Bass"]] = true,
    [L["Raw Sunscale Salmon"]] = true,
    [L["Raw Whitescale Salmon"]] = true,
    [L["Stonescale Eel"]] = true,
    [L["Winter Squid"]] = true,
    [L["Zesty Clam Meat"]] = true,
  },
}
M.filter_groups = groups

function M.isFilterGroup(str)
  return util.uniqueKeySearch(groups, str, util.strStartsWith)
end

function M.getFilterGroup(str)
  local name = isFilterGroup(str)
  return name and groups[name]
end

